theme = "tokyonight_storm"

[editor]
line-number = "relative"
auto-completion = true

[editor.statusline]
left = ["mode", "file-name"]
center = ["file-encoding", "file-type"]
right = ["diagnostics", "selections", "position"]
